logging:
  level:
    org.springframework.web: ERROR
    com.storyworld: ERROR
  path: D:\
server:
  servlet:
    context-path: /core
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storyworld?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.storyworld
    password: historyjka
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.transport.protocol: smtp
      mail.debug: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  kafka:
    consumer:
      group-id: anik
    bootstrap-servers:
    - localhost:9093
    template:
      default-topic: anik